apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sparkclusters.spark.k8s.io
spec:
  group: spark.k8s.io
  names:
    kind: SparkCluster
    listKind: SparkClusterList
    plural: sparkclusters
    singular: sparkcluster
  scope: Namespaced
  version: v1alpha1
