apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sparkclusters.cache.example.com
spec:
  group: cache.example.com
  names:
    kind: SparkCluster
    listKind: SparkClusterList
    plural: sparkclusters
    singular: sparkcluster
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
